// 20 个 Phase deck 的中文文案配置 —— 由 gen-phase-decks.mjs 消费
// 事实边界:课名/数量/hook/时间全部来自仓库实测;这里只写"阶段级"的解读文案。
export const PHASES = [
  {
    num: 0, slug: '00-setup-and-tooling', zh: '环境与工具',
    hook: ['一切算法,', '跑在环境之上。'],
    taglineNote: '工具链是后面 500 课的地基:环境配平一次,后面不再回头折腾。',
    themes: [
      ['终端与 Shell', '命令行是 AI 工程师的主场,图形界面只是补充。'],
      ['Git 工作流', '分支、提交、回滚——仓库纪律从第一课开始。'],
      ['Python 环境', 'venv、依赖固定、GPU 驱动,一次理清。'],
      ['调试与剖析', '会打断点、会看 profile,才配写复杂系统。'],
    ],
    build: { title: '把配置写成脚本', desc: '环境不靠记忆靠代码:安装、虚拟环境、别名全部脚本化,可重放、可分享。', list: ['一键重建开发环境的安装脚本', 'Git 分支与回滚工作流实操', '调试器与 profiler 上手'] },
    use: { title: '用成熟工具链', desc: '同一件事换业界标准工具再做一遍,搞清楚工具在替你做什么。', list: ['pip / venv 与依赖锁定', 'Docker 把环境固化成镜像', '云 GPU 与 API key 管理'] },
    manifesto: ['磨刀不误砍柴工。', '环境一次配平,', '五百课不再回头。'],
    manifestoNote: '本阶段没有算法,却决定后面每一课的体验:工具是复利,配一次吃全程。',
    closingBig: ['工具链配平,', '才配开始造。'],
    buildSummary: '一套可重放的开发环境:Shell、Git、Python、Docker、调试器全部脚本化。',
  },
  {
    num: 1, slug: '01-math-foundations', zh: '数学地基',
    hook: ['每个算法背后,', '都是一段数学。'],
    taglineNote: '不推公式背结论,而是用代码把直觉造出来:向量、矩阵、梯度、概率全部过手。',
    themes: [
      ['线性代数', '向量、矩阵、特征值——空间变换的语法。'],
      ['微积分与梯度', '链式法则亲手展开,自动微分不再神秘。'],
      ['概率与分布', '不确定性用分布描述,采样是基本动作。'],
      ['优化初步', '梯度下降:一切训练的地基循环。'],
    ],
    build: { title: '手写线性代数', desc: '向量、矩阵、Gram-Schmidt、QR 全部从零实现,Julia 并行版对照。', list: ['矩阵变换与特征值裸写', '链式法则手工展开到 autograd', '概率分布采样器从零实现'] },
    use: { title: 'NumPy / PyTorch 对照', desc: '同一运算换生产库再跑:rank、projection、QR 与张量 autograd 逐条印证。', list: ['NumPy 的 linalg 对照手写版', 'PyTorch 张量 + autograd 验证梯度', '生产库数值行为差异分析'] },
    manifesto: ['先有直觉。', '再上公式。', '公式从此可推导。'],
    manifestoNote: '数学课的失败模式是背了就忘;把每个概念写成代码,忘了随时能重造。',
    closingBig: ['直觉在手,', '公式不慌。'],
    buildSummary: '一套手写线性代数 + 微积分 + 概率工具箱,以及读论文不怕公式的底气。',
  },
  {
    num: 2, slug: '02-ml-fundamentals', zh: '机器学习基础',
    hook: ['生产 AI 的骨架,', '依然是经典 ML。'],
    taglineNote: '深度学习时代,线性回归、树模型、聚类仍是大多数生产系统的第一选择。',
    themes: [
      ['监督学习', '回归与分类:偏置、方差、正则的三角关系。'],
      ['树与集成', '决策树到梯度提升,表格数据之王。'],
      ['无监督学习', '聚类与降维:没有标签时如何看见结构。'],
      ['评估方法', '交叉验证与指标:防泄漏是纪律问题。'],
    ],
    build: { title: '手写经典模型', desc: '线性回归闭式解与梯度下降、决策树、k-means 全部裸写,损失与指标自己算。', list: ['最小二乘与梯度下降双实现', '决策树的信息增益分裂', 'k-means 与轮廓系数'] },
    use: { title: 'scikit-learn 对照', desc: '同一模型 sklearn 一行调用,读源码印证自己写的每个部件。', list: ['LinearRegression / GD 结果对齐', 'DecisionTree 与集成模型', 'Pipeline 与交叉验证规范'] },
    manifesto: ['经典不是过时。', '是生产线', '的骨架。'],
    manifestoNote: '大模型时代,表格数据上的冠军依然是梯度提升树;经典 ML 是最划算的投资。',
    closingBig: ['经典模型,', '仍是骨架。'],
    buildSummary: '一套手写经典模型族 + 一套严谨的评估方法论,足以支撑大多数表格类生产任务。',
  },
  {
    num: 3, slug: '03-deep-learning-core', zh: '深度学习核心',
    hook: ['想用框架?', '先自己造一个。'],
    taglineNote: '从单个神经元到手写反向传播,框架诞生之前的世界,拆开看透。',
    themes: [
      ['神经元与层', '前向传播是矩阵乘法加激活,仅此而已。'],
      ['反向传播', '计算图 + 链式法则,手写微型 autograd。'],
      ['训练循环', 'SGD、初始化、正则——训练稳定的全部手艺。'],
      ['优化器', '动量、Adam:为什么它们比 SGD 聪明。'],
    ],
    build: { title: '手写 autograd', desc: 'value-node 反向传播从零写起,在 XOR 与圆形分类边界上训练成功。', list: ['计算图节点与 backward 函数', '层与网络的组合封装', '手写训练循环跑通 XOR'] },
    use: { title: 'PyTorch 对照', desc: '同一网络换 nn.Module + autograd,数值逐条对齐,黑盒变透明。', list: ['nn.Linear 与手写层对照', 'autograd 梯度逐值校验', 'optim.Adam 与手写优化器'] },
    manifesto: ['框架不是黑盒。', '因为你写过', '它的迷你版。'],
    manifestoNote: '这个阶段是整条课程脊柱的原型:先 Build It 再 Use It,从反向传播开始一以贯之。',
    closingBig: ['框架之前,', '先造框架。'],
    buildSummary: '一个能跑的微型深度学习框架(手写 autograd + 训练循环),以及读穿 PyTorch 的能力。',
  },
  {
    num: 4, slug: '04-computer-vision', zh: '计算机视觉',
    hook: ['视觉不是魔法,', '是层层卷积。'],
    taglineNote: '从像素到检测与分割:卷积、增强、经典架构,28 课铺出一条看得见的路。',
    themes: [
      ['卷积网络', '卷积、池化、感受野:层级特征抽取的原语。'],
      ['经典架构', 'LeNet 到 ResNet:跳跃连接解决退化。'],
      ['检测与分割', '从滑窗到 anchor,从阈值到掩码。'],
      ['数据增强', '翻转、裁剪、Mixup:小数据的救命稻草。'],
    ],
    build: { title: '手写卷积', desc: '卷积核、池化、图像管线全部裸写,亲手看滤波器在原图上滑动。', list: ['二维卷积与 padding 裸实现', '池化与特征图可视化', '简易 CNN 在 MNIST/CIFAR 上训练'] },
    use: { title: 'PyTorch / torchvision', desc: 'nn.Conv2d 与预训练模型对照,迁移学习直接换头微调。', list: ['nn.Conv2d 数值对齐', 'ResNet 预训练骨干复用', 'torchvision 数据增强管线'] },
    manifesto: ['图像即数字。', '卷积即滤镜。', '视觉即层级特征。'],
    manifestoNote: '计算机视觉是「层级表示」最直观的证据:边缘→纹理→部件→物体,层层组合。',
    closingBig: ['让机器', '看见。'],
    buildSummary: '手写卷积网络 + 会用预训练骨干做迁移,能独立完成分类、检测、分割任务。',
  },
  {
    num: 5, slug: '05-nlp-foundations-to-advanced', zh: '自然语言处理',
    hook: ['从字符到语义,', 'NLP 全链路。'],
    taglineNote: '29 课从分词走到 Transformer 之前夜:文本怎么变成机器可计算的表示。',
    themes: [
      ['文本预处理', '分词、词干化、停用词:一切从切开开始。'],
      ['表示学习', 'TF-IDF、词向量:语义进入几何空间。'],
      ['序列模型', 'RNN/LSTM:带记忆的网络与梯度问题。'],
      ['任务与评估', '分类、NER、生成:指标各有脾气。'],
    ],
    build: { title: '手写文本管线', desc: '分词、TF-IDF、n-gram 语言模型全部裸写,亲手搭文本分类器。', list: ['BPE 思想的简化实现', 'TF-IDF 与余弦相似度检索', 'n-gram 语言模型与困惑度'] },
    use: { title: '生产 NLP 栈', desc: '预训练 tokenizer 与词向量对照,理解子词切分为何赢。', list: ['生产 tokenizer 对照手写版', '预训练词向量相似度验证', 'seq2seq 评估指标实操'] },
    manifesto: ['语言先被切开。', '再被理解。', '最后被生成。'],
    manifestoNote: 'NLP 是「表示的进化史」:one-hot → 稠密词向量 → 上下文表示,每一步都在逼近语义。',
    closingBig: ['让机器', '读懂语言。'],
    buildSummary: '一条完整的手写文本管线 + 表示学习直觉,衔接 Phase 07 的 Transformer。',
  },
  {
    num: 6, slug: '06-speech-and-audio', zh: '语音与音频',
    hook: ['让机器听懂,', '从波形开始。'],
    taglineNote: '17 课把振动变成特征、把特征变成词:音频的表示与识别全链路。',
    themes: [
      ['音频信号', '采样、频谱、窗函数:声音的数学画像。'],
      ['声学特征', 'MFCC / 滤波器组:人耳启发的压缩。'],
      ['识别与合成', '声学模型到 TTS:双向的语音通路。'],
      ['流式处理', '实时音频管线与 VAD 的工程细节。'],
    ],
    build: { title: '手写音频特征', desc: '从原始波形出发,STFT、梅尔滤波器组、MFCC 逐级裸写。', list: ['STFT 与频谱图实现', '梅尔滤波器组手工构造', '动态时间规整 DTW 对齐'] },
    use: { title: 'librosa / torchaudio', desc: '同一特征换生产库,数值对齐后直接进生产管线。', list: ['librosa 特征数值对照', 'torchaudio 流式特征', '预训练 ASR 模型试用'] },
    manifesto: ['声音是振动。', '特征是压缩。', '识别是概率。'],
    manifestoNote: '音频课的全部魔法都在「表示」:把一维振动压成二维时频图,问题就变成了视觉问题。',
    closingBig: ['让机器', '听清世界。'],
    buildSummary: '手写声学特征管线 + 会用生产语音栈,理解 ASR/TTS 系统的每个接口。',
  },
  {
    num: 7, slug: '07-transformers-deep-dive', zh: 'Transformer 深潜',
    hook: ['读懂 Transformer,', '从手写 attention。'],
    taglineNote: '16 课把当代 AI 的核心组件拆到螺丝级:scaled dot-product、多头、位置编码。',
    themes: [
      ['注意力机制', 'Q/K/V 加权查表:一切的起点。'],
      ['多头与位置', '多头并行与位置编码的分工。'],
      ['三种架构', 'encoder-only / decoder-only / enc-dec 各司其职。'],
      ['训练细节', 'mask、warmup、KV 缓存:能跑与能用的距离。'],
    ],
    build: { title: '手写 attention', desc: 'scaled dot-product、multi-head、causal mask 全部裸写,数值可对齐。', list: ['注意力打分与 softmax 裸实现', '多头切分与拼接', 'KV 缓存推理加速手写'] },
    use: { title: 'nn.MultiheadAttention', desc: '与生产实现对齐数值,读源码确认每个超参的真实作用。', list: ['官方模块数值校验', '位置编码方案对比实验', 'HuggingFace 配置逐项解读'] },
    manifesto: ['一切皆注意力。', '手写一遍,', 'Transformer 透明。'],
    manifestoNote: 'Transformer 是当代 AI 的汇编语言:这一阶段之后,读任何架构论文都有抓手。',
    closingBig: ['注意力,', '亲手点亮。'],
    buildSummary: '一套手写 Transformer 组件 + 读穿任意变体架构的能力,LLM 时代的通行证。',
  },
  {
    num: 8, slug: '08-generative-ai', zh: '生成式 AI',
    hook: ['会判别还不够,', '要会生成。'],
    taglineNote: '15 课从自编码器走到扩散模型:学习数据分布,然后从分布里采样创造。',
    themes: [
      ['自编码器', '压缩与重建:表示学习的第一课。'],
      ['VAE', '隐空间的概率化:能插值、能采样。'],
      ['GAN', '生成器与判别器的博弈训练。'],
      ['扩散模型', '加噪去噪:当代图像生成的引擎。'],
    ],
    build: { title: '手写生成核心', desc: 'AE/VAE 的编码解码与重参数化、扩散的前向加噪与反向采样裸写。', list: ['VAE 重参数化技巧实现', 'DDPM 前向噪声计划表', '简版采样循环出图'] },
    use: { title: '生产生成栈', desc: '对照生产 pipeline 的采样器与调度器,理解每步去噪的意义。', list: ['扩散 pipeline 调度器对照', '预训练模型微调试验', '生成质量评估指标'] },
    manifesto: ['判别学边界。', '生成学分布。', '分布在手,创作自由。'],
    manifestoNote: '生成模型的统一视角是「学分布」:VAE 显式学,GAN 对抗学,扩散迭代学。',
    closingBig: ['从判别', '到生成。'],
    buildSummary: '三类生成模型的手写实现 + 会用生产管线,理解 AIGC 产品背后的引擎。',
  },
  {
    num: 9, slug: '09-reinforcement-learning', zh: '强化学习',
    hook: ['智能不是写的,', '是练出来的。'],
    taglineNote: '12 课从多臂老虎机到策略梯度:试错、奖励、更新,智能的另一种学法。',
    themes: [
      ['探索与利用', '多臂老虎机:最早的决策困境。'],
      ['动态规划', 'Bellman 方程:价值迭代的数学核。'],
      ['无模型方法', 'Q-learning 与 SARSA:从经验里学价值。'],
      ['策略梯度', '直接对策略求导:走向现代 RL。'],
    ],
    build: { title: '手写 RL 核心', desc: 'Q-learning、SARSA、REINFORCE 表格版全部裸写,在网格世界里收敛。', list: ['ε-greedy 探索策略实现', 'Q-learning 收敛曲线', '策略梯度最小可运行版'] },
    use: { title: 'RL 框架对照', desc: 'gym 环境接口 + 标准实现对照,理解工程化补齐了什么。', list: ['gymnasium 环境封装', '基准实现结果对照', '超参与稳定性分析'] },
    manifesto: ['试错、奖励、更新。', '智能是', '迭代出来的。'],
    manifestoNote: 'RL 是唯一「数据由自己行为产生」的学习范式,也是 LLM 对齐(RLHF)的技术根。',
    closingBig: ['奖励之下', '必有学习。'],
    buildSummary: '手写表格级 RL 算法族 + 会用标准环境与基准,读懂 RLHF 的前置一切就绪。',
  },
  {
    num: 10, slug: '10-llms-from-scratch', zh: '从零造 LLM',
    hook: ['LLM 没有魔法,', '只有概率。'],
    taglineNote: '24 课把 GPT 拆到零件级:tokenizer、注意力块、训练循环、采样策略全手作。',
    themes: [
      ['Tokenizer', 'BPE:字符串变成 token 序列。'],
      ['架构组装', 'embedding + attention + FFN = 块,堆 N 层。'],
      ['预训练', '下一词预测:目标简单,工程浩大。'],
      ['解码与对齐', '温度、top-p、SFT:从会接话到会听话。'],
    ],
    build: { title: '手写 mini-GPT', desc: '从 BPE 到完整训练循环,一个小语料上的语言模型全栈裸写。', list: ['BPE 训练与编解码实现', 'GPT 块堆叠与参数初始化', '温度 / top-p 采样器'] },
    use: { title: 'HuggingFace 对照', desc: '同结构生产实现对照,读懂配置文件里每个开关。', list: ['生产 tokenizer 对齐', '模型配置逐项映射', '生成参数行为复现'] },
    manifesto: ['下一词的概率。', '拆开 LLM,', '不过如此。'],
    manifestoNote: '这一阶段把「大」还原成「小」:当你亲手训过 10M 参数的 GPT,175B 不再是神话。',
    closingBig: ['LLM,', '自己造。'],
    buildSummary: '一个完整可训练的 mini-GPT + 对生产 LLM 全栈的逐层理解。',
  },
  {
    num: 11, slug: '11-llm-engineering', zh: 'LLM 工程',
    hook: ['调用 API 之后,', '工程才开始。'],
    taglineNote: '17 课把模型变成系统:prompt 工程、结构化输出、评估、缓存、成本控制。',
    themes: [
      ['Prompt 工程', 'few-shot、CoT、结构化指令:接口设计学。'],
      ['结构化输出', 'JSON schema 与解析容错:下游的命脉。'],
      ['评估体系', 'golden set + LLM-as-judge:可测才可改。'],
      ['成本与延迟', '缓存、路由、批处理:性价比工程。'],
    ],
    build: { title: '手写 LLM 工作流', desc: 'prompt 模板引擎、输出解析重试、评估打分脚本全部裸写。', list: ['模板变量与 few-shot 注入', 'JSON 解析失败的降级重试', '评估集与打分器实现'] },
    use: { title: '生产框架对照', desc: '结构化输出与可观测工具对照,理解生产补齐的每一块板。', list: ['结构化输出模式对照', '追踪与可观测性接入', '成本核算与缓存策略'] },
    manifesto: ['prompt 是接口。', '评估是地基。', '工程化才可复用。'],
    manifestoNote: 'LLM 工程的分水岭在评估:没有 golden set 的团队,每次改 prompt 都在赌。',
    closingBig: ['能评估', '才可工程。'],
    buildSummary: '一套可复用的 LLM 应用工程件:模板、解析、评估、缓存,直接用于生产。',
  },
  {
    num: 12, slug: '12-multimodal-ai', zh: '多模态 AI',
    hook: ['看、听、读,', '一个模型全包。'],
    taglineNote: '25 课把视觉与语言装进同一空间:对齐、融合、生成的完整地图。',
    themes: [
      ['视觉语言模型', '图像编码器 + 语言模型:VLM 的组装术。'],
      ['对齐预训练', 'CLIP 式对比学习:跨模态的桥。'],
      ['生成跨模态', '文生图、图像编辑的条件控制。'],
      ['语音多模态', ' Whisper 类模型:听与说的统一。'],
    ],
    build: { title: '手写跨模态对齐', desc: '图文对比学习最小实现,亲手把两个模态拉进同一空间。', list: ['双塔编码器与对比损失', '小数据上的检索实验', 'cross-attention 融合裸写'] },
    use: { title: 'CLIP 类模型对照', desc: '预训练对齐模型零样本试验,理解表示空间的通用性。', list: ['CLIP 零样本分类复现', '图文检索 pipeline', 'VLM 推理与提示技巧'] },
    manifesto: ['文本、图像、声音。', '对齐在', '同一个空间。'],
    manifestoNote: '多模态的核心问题不是「更大」,而是「对齐」:不同模态的语义要能互相翻译。',
    closingBig: ['世界不止', '文字。'],
    buildSummary: '跨模态对齐的手写实现 + 会组装 VLM,多模态产品的基本功齐了。',
  },
  {
    num: 13, slug: '13-tools-and-protocols', zh: '工具与协议',
    hook: ['工具要互通,', '协议是桥。'],
    taglineNote: '31 课让模型长出手脚:函数调用、schema、MCP、工具生态的工程化。',
    themes: [
      ['函数调用', 'schema 设计与参数校验:模型的 API。'],
      ['MCP 协议', 'server / client / 传输层:标准化的工具总线。'],
      ['安全边界', '注入防御与权限最小化。'],
      ['工具生态', '注册、发现、组合:从工具到平台。'],
    ],
    build: { title: '手写工具协议', desc: 'JSON schema 校验、tool-call 解析、执行循环裸写,不借助任何 SDK。', list: ['schema 校验器实现', 'tool-call 解析与重试', '最小 tool 执行沙箱'] },
    use: { title: 'MCP SDK 对照', desc: '用生产 SDK 实现同一 server,对照传输、能力协商与错误处理。', list: ['MCP server 生产实现', 'stdio / HTTP 传输对照', '注册表与发现机制'] },
    manifesto: ['协议是约定。', '约定让', '工具互通。'],
    manifestoNote: '工具生态的胜负手是协议:MCP 之于工具,约等于 HTTP 之于文档。',
    closingBig: ['协议通,', '工具通。'],
    buildSummary: '手写工具调用全链路 + 一个符合协议的 MCP server,模型从此长手长脚。',
  },
  {
    num: 14, slug: '14-agent-engineering', zh: 'Agent 工程',
    hook: ['agent 的本质,', '是一个循环。'],
    taglineNote: '42 课的全课程最大阶段:感知、记忆、规划、工具、反思,agent 的五脏六腑。',
    themes: [
      ['Agent 循环', 'think → act → observe:最小智能单元。'],
      ['记忆系统', '短期上下文与长期记忆的分层设计。'],
      ['规划与任务分解', '把大目标切成可执行的小步。'],
      ['可靠性', '重试、护栏、评估:从 demo 到生产。'],
    ],
    build: { title: '手写 agent loop', desc: '不借助框架,从消息循环开始实现一个能自主使用工具的 agent。', list: ['ReAct 式循环实现', '工具注册与调用层', '短期记忆窗口管理'] },
    use: { title: 'agent 框架对照', desc: '对照成熟框架的抽象:状态机、检查点、人机协同各在哪一层。', list: ['框架状态管理对照', '多轮任务检查点', 'human-in-the-loop 接入'] },
    manifesto: ['感知、决策、行动。', '循环转起来,', '才是 agent。'],
    manifestoNote: 'agent 工程的难点不在循环本身,而在循环失败后的每一条退路。',
    closingBig: ['循环即', '智能。'],
    buildSummary: '一个从零手写的可用 agent + 用框架重构的对照版,生产级可靠性清单在手。',
  },
  {
    num: 15, slug: '15-autonomous-systems', zh: '自主系统',
    hook: ['把方向盘,', '交给系统。'],
    taglineNote: '22 课把 agent 推向自主:长程规划、自我反思、目标管理与人机边界。',
    themes: [
      ['长程规划', '目标分解与依赖排序:跑得远靠地图。'],
      ['自我反思', '执行后复盘:失败是最好的人类反馈。'],
      ['状态与恢复', '检查点与断点续跑:长任务的保险。'],
      ['人机边界', '什么时候该问人:自治的刻度尺。'],
    ],
    build: { title: '手写规划器', desc: 'plan → execute → reflect 闭环裸写,任务图与重规划逻辑自己实现。', list: ['任务图依赖调度', '反思驱动的重规划', '执行状态持久化'] },
    use: { title: '编排框架对照', desc: '对照生产编排器,理解可观测与可控性是自治的前提。', list: ['编排器状态机对照', '长任务监控接入', '审批流与熔断设计'] },
    manifesto: ['自己定计划。', '自己执行。', '自己复盘。'],
    manifestoNote: '自主性不是开关而是旋钮:每一档都对应不同的护栏与回退路径。',
    closingBig: ['规划、行动、', '反思。'],
    buildSummary: '一个带反思与恢复能力的自主执行器,以及「何时交还人类」的设计判断。',
  },
  {
    num: 16, slug: '16-multi-agent-and-swarms', zh: '多智能体与集群',
    hook: ['单个不够,', '组队。'],
    taglineNote: '25 课从对话到协作:角色分工、消息传递、群体决策的编排艺术。',
    themes: [
      ['角色分工', '规划者、执行者、批评者:结构即能力。'],
      ['消息传递', 'agent 间协议:广播、点对点、黑板。'],
      ['群体决策', '投票、辩论、共识:质量从何而来。'],
      ['编排与成本', '调度、共享上下文、省钱的设计。'],
    ],
    build: { title: '手写消息传递', desc: 'agent 间消息协议与调度器裸写,实现辩论与分工两种协作模式。', list: ['消息总线与订阅机制', '辩论式双 agent 实现', '共享内存黑板模式'] },
    use: { title: 'swarm 框架对照', desc: '对照生产多智能体框架,理解编排层替你扛了哪些复杂度。', list: ['框架编排拓扑对照', '成本与延迟核算', '失败传播与隔离'] },
    manifesto: ['一个 agent 是工具。', '一群 agent', '是系统。'],
    manifestoNote: '多智能体的第一性问题是「通信成本」:消息越少越准,系统越稳。',
    closingBig: ['群体', '大于个体。'],
    buildSummary: '两种协作模式的手写实现 + 生产编排对照,能设计多 agent 系统的拓扑。',
  },
  {
    num: 17, slug: '17-infrastructure-and-production', zh: '基建与生产',
    hook: ['从 notebook', '到生产。'],
    taglineNote: '28 课补齐最后一公里:服务化、观测、扩缩容、灰度发布与故障恢复。',
    themes: [
      ['服务化', '推理服务封装:批处理与流式接口。'],
      ['可观测性', '日志、指标、追踪:看不见就修不了。'],
      ['扩缩容', '负载、队列、GPU 利用率的经济学。'],
      ['发布与恢复', '灰度、回滚、降级:变化的安全网。'],
    ],
    build: { title: '手写部署脚本', desc: '模型服务封装、健康检查、结构化日志与限流裸写。', list: ['推理服务最小实现', '健康检查与优雅停机', '结构化日志与指标暴露'] },
    use: { title: '生产基建对照', desc: '对照容器化与监控栈,理解生产环境多出来的每一层。', list: ['Docker / 编排部署', '监控告警面板接入', '灰度发布与回滚演练'] },
    manifesto: ['能 demo 不算完。', '能上线、能观测、', '能恢复才算完。'],
    manifestoNote: '生产阶段的全部内容都围绕一个词:变化——流量会变、模型会变、故障会来。',
    closingBig: ['上线,', '只是开始。'],
    buildSummary: '一套手写的推理服务 + 完整的可观测与发布方案,系统不再怕凌晨三点。',
  },
  {
    num: 18, slug: '18-ethics-safety-alignment', zh: '伦理、安全与对齐',
    hook: ['强大的模型,', '需要更强的护栏。'],
    taglineNote: '30 课严肃对待风险:偏见、越狱、评测、治理——对齐是工程不是态度。',
    themes: [
      ['偏见与公平', '数据偏见如何进入模型,又如何度量。'],
      ['对抗与越狱', '攻击面分析:提示注入到数据投毒。'],
      ['评测与红线', '安全评测集与拒答边界的设计。'],
      ['治理与审计', '文档、追溯、合规:组织的护栏。'],
    ],
    build: { title: '手写评估与攻击', desc: 'red-team 脚本、偏见度量、安全评测集全部裸写。', list: ['提示注入攻击用例集', '偏见基准的度量实现', '拒答边界评测器'] },
    use: { title: 'guardrails 库对照', desc: '对照生产护栏与审计工具,把安全从脚本升级成流程。', list: ['输入输出护栏接入', '审计日志与追溯链', '红队演练流程'] },
    manifesto: ['能力与风险同涨。', '护栏是', '对齐的日常。'],
    manifestoNote: '安全不是发版前的一次检查,而是与能力同步迭代的工程学科。',
    closingBig: ['先立护栏,', '再谈能力。'],
    buildSummary: '一套手写的安全评测与攻击工具 + 生产护栏方案,把「负责任」落成清单。',
  },
  {
    num: 19, slug: '19-capstone-projects', zh: '毕业项目',
    hook: ['五百课,', '交付成产品。'],
    taglineNote: '85 课 = 17 个端到端产品 + 9 条深度构建线,每项目 20-40 小时的真刀真枪。',
    themes: [
      ['端到端产品', '从需求到部署:17 个完整作品。'],
      ['深度构建线', '9 条主线:把一个方向打穿。'],
      ['工程整合', '前面 18 个阶段的工具箱全面实战。'],
      ['作品集', '可展示、可维护、可讲述的产出。'],
    ],
    build: { title: '手写完整产品', desc: '没有脚手架,从空目录开始:需求、设计、实现、部署、文档一人全链。', list: ['需求拆解与里程碑', '核心功能全手作实现', '部署上线与 README'] },
    use: { title: '面向真实发布', desc: '对照真实产品的迭代节奏:用户反馈、版本、维护一个都不少。', list: ['版本管理与 changelog', '真实用户反馈循环', '维护与二次迭代'] },
    manifesto: ['五百课的终点。', '是别人', '起点的地方。'],
    manifestoNote: '毕业项目是整条课程的验收标准:所有 Build It / Use It 的手艺,在这里拼成作品。',
    closingBig: ['此刻,', '交付。'],
    buildSummary: '至少一个端到端上线的作品 + 一条打穿的深度方向,作品集正式开张。',
  },
];
